module WebfleetConnect::Enums::VehicleTypes
  def ape()                       :ape                       end
  def barge()                     :barge                     end
  def bike()                      :bike                      end
  def boom_lift()                 :boom_lift                 end
  def boom_lift_truck()           :boom_lift_truck           end
  def bus()                       :bus                       end
  def caddy()                     :caddy                     end
  def car()                       :car                       end
  def car_station_wagon()         :car_station_wagon         end
  def concrete_lorry()            :concrete_lorry            end
  def containership()             :containership             end
  def crane()                     :crane                     end
  def deposit_tipper()            :deposit_tipper            end
  def dump_truck()                :dump_truck                end
  def dump_truck_open()           :dump_truck_open           end
  def excavator()                 :excavator                 end
  def garbage_truck()             :garbage_truck             end
  def heavy_truck()               :heavy_truck               end
  def heavytruck_us()             :heavytruck_us             end
  def heavyweight_truck()         :heavyweight_truck         end
  def heavyweight_truck_trailer() :heavyweight_truck_trailer end
  def lighttruck()                :lighttruck                end
  def light_truck_pallet()        :light_truck_pallet        end
  def loader()                    :loader                    end
  def medium_truck()              :medium_truck              end
  def multicar()                  :multicar                  end
  def multivan()                  :multivan                  end
  def pallet_truck()              :pallet_truck              end
  def pickup()                    :pickup                    end
  def smart()                     :smart                     end
  def sprinter()                  :sprinter                  end
  def street_sweeper()            :street_sweeper            end
  def suv()                       :suv                       end
  def tanker_truck()              :tanker_truck              end
  def telescopic_handler()        :telescopic_handler        end
  def tractor()                   :tractor                   end
  def trailer()                   :trailer                   end
  def train()                     :train                     end
  def truck()                     :truck                     end
  def truck_loader_arm()          :truck_loader_arm          end
  def truck_trailer()             :truck_trailer             end
  def truck_with_trailer()        :truck_with_trailer        end
  def truck_wrecker()             :truck_wrecker             end
  def van()                       :van                       end
  def vespa()                     :vespa                     end
  def wrecker()                   :wrecker                   end
  def yacht()                     :yacht                     end
end
